### ISSUE TITLE
crash after resuming computer from sleep

### ISSUE THREAD

**Issue by cweiske** [psi-im/psi#293]
Version: psi+ 1.0.116 from ubuntu ppa

After resuming my computer from sleep, Psi+ crashed. Here is the gdb backtrace:

```
[20170703 8:20:58] Unknown signature value:  795 (unknown:0, unknown)
[20170703 8:20:58] Unknown signature value:  7 (unknown:0, unknown)
[20170703 8:20:58] Unknown signature value:  795 (unknown:0, unknown)
[20170703 8:20:58] Unknown signature value:  795 (unknown:0, unknown)
[20170703 8:20:58] Unknown signature value:  795 (unknown:0, unknown)
[20170703 8:20:58] Unknown signature value:  794 (unknown:0, unknown)
[20170703 8:20:58] Unknown signature value:  795 (unknown:0, unknown)
[20170703 8:20:58] Unknown signature value:  795 (unknown:0, unknown)
[New Thread 0x7fffaffff700 (LWP 3269)]
[New Thread 0x7fffbbfff700 (LWP 3270)]
[20170703 8:20:59] unexpected version response (unknown:0, unknown)
[20170703 8:20:59] unexpected version response (unknown:0, unknown)
[20170703 8:20:59] unexpected version response (unknown:0, unknown)
[20170703 8:20:59] unexpected version response (unknown:0, unknown)
[20170703 8:20:59] W:"WARNING! VCard::image2type: unknown format = ''" (unknown:0, unknown)

Thread 1 "psi-plus" received signal SIGSEGV, Segmentation fault.
PsiContact::jid (this=<optimized out>) at /build/psi-plus-lKnO8o/psi-plus-1.0.113/src/psicontact.cpp:223
223	/build/psi-plus-lKnO8o/psi-plus-1.0.113/src/psicontact.cpp: Datei oder Verzeichnis nicht gefunden.
(gdb) thr a all bt full
Thread 39 (Thread 0x7fffb8b67700 (LWP 25619)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
No locals.
#1  0x00007ffff5be5996 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#2  0x00007ffff5be1463 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#3  0x00007ffff5be47be in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#4  0x00007ffff44a86ba in start_thread (arg=0x7fffb8b67700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffb8b67700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736292353792, 6674263309673159823, 0, 140737488340943, 140736292354496, 93825026016336, -6674107656237622129, -6674238392134804337}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 
              0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007ffff4fdb3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 38 (Thread 0x7fffb9368700 (LWP 25618)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
No locals.
#1  0x00007ffff5be5996 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#2  0x00007ffff5be1463 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#3  0x00007ffff5be47be in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#4  0x00007ffff44a86ba in start_thread (arg=0x7fffb9368700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffb9368700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736300746496, 6674263309673159823, 0, 140737488341999, 140736300747200, 93825026965312, -6674108755212378993, -6674238392134804337}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 
              0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007ffff4fdb3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 37 (Thread 0x7fffb9b69700 (LWP 25617)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
No locals.
#1  0x00007ffff5be5996 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#2  0x00007ffff5be1463 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#3  0x00007ffff5be47be in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#4  0x00007ffff44a86ba in start_thread (arg=0x7fffb9b69700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffb9b69700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736309139200, 6674263309673159823, 0, 140737488342127, 140736309139904, 93825026670272, -6674109852039652209, -6674238392134804337}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 
              0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007ffff4fdb3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 36 (Thread 0x7fffba36a700 (LWP 25616)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
No locals.
#1  0x00007ffff5be5996 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#2  0x00007ffff5be1463 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#3  0x00007ffff5be47be in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#4  0x00007ffff44a86ba in start_thread (arg=0x7fffba36a700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffba36a700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736317531904, 6674263309673159823, 0, 140737488341999, 140736317532608, 93825025840048, -6674110951014409073, -6674238392134804337}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 
              0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007ffff4fdb3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 35 (Thread 0x7fffbbfff700 (LWP 25615)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
No locals.
#1  0x00007ffff5be5996 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#2  0x00007ffff5be1463 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#3  0x00007ffff5be47be in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#4  0x00007ffff44a86ba in start_thread (arg=0x7fffbbfff700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffbbfff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736347502336, 6674263309673159823, 0, 140737488341999, 8388608, 93825026756416, -6674113776566018929, -6674238392134804337}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, 
            data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007ffff4fdb3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 13 (Thread 0x7fffca210700 (LWP 9343)):
#0  0x00007ffff4fcf70d in poll () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x00007ffff3d6638c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007ffff3d6649c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007ffff5e1b7cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#4  0x00007ffff5dc2b4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#5  0x00007ffff5bdf834 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#6  0x00007ffff5be47be in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#7  0x00007ffff44a86ba in start_thread (arg=0x7fffca210700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffca210700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736584550144, 6674263309673159823, 0, 140737488343423, 8388608, 93825026671120, -6674286957700457329, -6674238392134804337}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, 
            data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#8  0x00007ffff4fdb3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 12 (Thread 0x7fffc9a0f700 (LWP 6660)):
#0  0x00007ffff4fcf70d in poll () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x00007ffff3d6638c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007ffff3d66712 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fffe8ec99d6 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007ffff3d8cbb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007ffff44a86ba in start_thread (arg=0x7fffc9a0f700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffc9a0f700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736576157440, 6674263309673159823, 0, 140737488337855, 8388608, 93825026989280, -6674285858725700465, -6674238392134804337}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, 
            data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#6  0x00007ffff4fdb3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 11 (Thread 0x7fffcaa11700 (LWP 6659)):
#0  0x00007ffff4fcf70d in poll () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x00007ffff3d6638c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007ffff3d6649c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007ffff3d664d9 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007ffff3d8cbb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007ffff44a86ba in start_thread (arg=0x7fffcaa11700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffcaa11700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736592942848, 6674263309673159823, 0, 140737488337503, 8388608, 93825026017296, -6674288071707599729, -6674238392134804337}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, 
            data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#6  0x00007ffff4fdb3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 5 (Thread 0x7fffcc282700 (LWP 6620)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
No locals.
#1  0x00007fffcf9950f3 in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
No symbol table info available.
#2  0x00007fffcf994817 in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
No symbol table info available.
#3  0x00007ffff44a86ba in start_thread (arg=0x7fffcc282700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffcc282700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736618571520, 6674263309673159823, 0, 140737488336447, 140736618572224, 140737488338976, -6674291429835154289, -6674238392134804337}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 
              0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#4  0x00007ffff4fdb3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 4 (Thread 0x7fffd7b88700 (LWP 6619)):
#0  0x00007ffff4fcf70d in poll () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x00007ffff3d6638c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007ffff3d6649c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007ffff5e1b7cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#4  0x00007ffff5dc2b4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#5  0x00007ffff5bdf834 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#6  0x00007ffff5be47be in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#7  0x00007ffff44a86ba in start_thread (arg=0x7fffd7b88700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffd7b88700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736812582656, 6674263309673159823, 0, 140737488341183, 140736812583360, 93825021553808, -6674316580089897841, -6674238392134804337}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 
              0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#8  0x00007ffff4fdb3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 3 (Thread 0x7fffddb13700 (LWP 6607)):
#0  0x00007ffff4fcf70d in poll () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x00007ffff3d6638c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007ffff3d6649c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007ffff5e1b7cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#4  0x00007ffff5dc2b4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#5  0x00007ffff761bce5 in QCA::SyncThread::run() () from /usr/lib/x86_64-linux-gnu/libqca-qt5.so.2
No symbol table info available.
#6  0x00007ffff5be47be in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#7  0x00007ffff44a86ba in start_thread (arg=0x7fffddb13700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffddb13700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736912766720, 6674263309673159823, 0, 140737488345455, 140736912767424, 93825007333424, -6674329716784243569, -6674238392134804337}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 
              0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#8  0x00007ffff4fdb3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 2 (Thread 0x7fffeb47b700 (LWP 6606)):
#0  0x00007ffff4fcf70d in poll () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x00007ffff7884c62 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
No symbol table info available.
#2  0x00007ffff78868d7 in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
No symbol table info available.
#3  0x00007fffed9d0889 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
No symbol table info available.
#4  0x00007ffff5be47be in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#5  0x00007ffff44a86ba in start_thread (arg=0x7fffeb47b700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffeb47b700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737140733696, 6674263309673159823, 0, 140737488344271, 140737140734400, 93825005029568, -6674218575915524977, -6674238392134804337}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 
              0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#6  0x00007ffff4fdb3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 1 (Thread 0x7ffff7e0c8c0 (LWP 6601)):
#0  PsiContact::jid (this=<optimized out>) at /build/psi-plus-CloWZN/psi-plus-1.0.116/src/psicontact.cpp:223
No locals.
#1  0x00005555559365bc in ContactListItem::value (this=0x55555bae3140, role=role@entry=259) at /build/psi-plus-CloWZN/psi-plus-1.0.116/src/contactlistitem.cpp:453
        res = {d = {data = {c = 0 '\000', uc = 0 '\000', s = 0, sc = 0 '\000', us = 0, i = 0, u = 0, l = 0, ul = 0, b = false, d = 0, f = 0, real = 0, ll = 0, ull = 0, o = 0x0, ptr = 0x0, shared = 0x0}, type = 0, is_shared = 0, 
            is_null = 1}}
#2  0x0000555555937ef6 in ContactListModel::data (this=<optimized out>, index=..., role=259) at /build/psi-plus-CloWZN/psi-plus-1.0.116/src/contactlistmodel.cpp:598
        item = 0x55555bae3140
#3  0x0000555555882277 in QModelIndex::data (arole=259, this=0x7fffffffcf90) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qabstractitemmodel.h:420
No locals.
#4  PsiRosterFilterProxyModel::filterAcceptsRow (this=0x55555bc90080, sourceRow=104, sourceParent=...) at /build/psi-plus-CloWZN/psi-plus-1.0.116/src/psirosterwidget.cpp:84
        index = {r = 104, c = 0, i = 93825098723648, m = 0x55555bada410}
        data = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = -1}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, 
                d = 0x7ffff5e99580 <QListData::shared_null>}, d = 0x7ffff5e99580 <QListData::shared_null>}}, <No data fields>}
#5  0x00007ffff5d8f437 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#6  0x00007ffff5d909c1 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#7  0x00007ffff5d911fb in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#8  0x00007ffff5d964fb in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#9  0x00007ffff5df3d2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#10 0x00007ffff5e6ff16 in QAbstractItemModel::layoutChanged(QList<QPersistentModelIndex> const&, QAbstractItemModel::LayoutChangeHint) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#11 0x00005555559396bf in ContactListModel::Private::addContacts (this=this@entry=0x55555c237fa0, contacts=...) at /build/psi-plus-CloWZN/psi-plus-1.0.116/src/contactlistmodel.cpp:153
        slowTimer = {_timer = {t1 = 283627, t2 = 30618149}, _path = {static null = {<No data fields>}, d = 0x5555571b7010}, _line = 144, _message = {static null = {<No data fields>}, d = 0x7ffff5e983e0 <QArrayData::shared_null>}, 
          _maxTime = 100}
#12 0x000055555593a9e3 in ContactListModel::Private::commit (this=0x55555c237fa0) at /build/psi-plus-CloWZN/psi-plus-1.0.116/src/contactlistmodel.cpp:296
        slowTimer = {_timer = {t1 = 283627, t2 = 29514769}, _path = {static null = {<No data fields>}, d = 0x55555be87d40}, _line = 257, _message = {static null = {<No data fields>}, d = 0x7ffff5e983e0 <QArrayData::shared_null>}, 
          _maxTime = 100}
        it = {c = {{d = 0x55555c294bf0, e = 0x55555c294bf0}}, i = {i = 0x55555c294bf0}, n = {i = 0x55555b9c49f0}}
        contactsForAdding = {<QListSpecialMethods<PsiContact*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = -1}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x55555becaa80}, d = 0x55555becaa80}}
        contactsForUpdate = {<QListSpecialMethods<PsiContact*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = -1}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x55555b9d0e60}, d = 0x55555b9d0e60}}
#13 0x00005555558a8d15 in ContactListModel::Private::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>)
    at /build/psi-plus-CloWZN/psi-plus-1.0.116/debian/builddir1/src/moc_contactlistmodel_p.cpp:97
        _t = <optimized out>
#14 0x00007ffff5df3d2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#15 0x00007ffff5e005c8 in QTimer::timerEvent(QTimerEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#16 0x00007ffff5df4bb3 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#17 0x00007ffff673605c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#18 0x00007ffff673b516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#19 0x00007ffff5dc538b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#20 0x00007ffff5e1a5ed in QTimerInfoList::activateTimers() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#21 0x00007ffff5e1ab29 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#22 0x00007ffff3d66197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#23 0x00007ffff3d663f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#24 0x00007ffff3d6649c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#25 0x00007ffff5e1b7cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#26 0x00007ffff5dc2b4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#27 0x00007ffff5dcabec in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#28 0x0000555555791f48 in main (argc=1, argv=<optimized out>) at /build/psi-plus-CloWZN/psi-plus-1.0.116/src/main.cpp:611
        cli = {<SimpleCli> = {<QObject> = {<No data fields>}, argdefs = {d = 0x55555615af80}, aliases = {d = 0x55555615a5d0}}, static staticMetaObject = {d = {superdata = 0x7ffff6005b00 <QObject::staticMetaObject>, 
              stringdata = 0x555555d12c20 <qt_meta_stringdata_PsiCli>, data = 0x555555d12be0 <qt_meta_data_PsiCli>, static_metacall = 0x5555558b5ef0 <PsiCli::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, 
              relatedMetaObjects = 0x0, extradata = 0x0}}}
        cmdline = {{d = 0x7ffff5e99520 <QHashData::shared_null>, e = 0x7ffff5e99520 <QHashData::shared_null>}}
        init = {<No data fields>}
        app = {<QApplication> = {<No data fields>}, static staticMetaObject = {d = {superdata = 0x7ffff6c38140 <QApplication::staticMetaObject>, stringdata = 0x555555d12360 <qt_meta_stringdata_PsiApplication>, 
              data = 0x555555d122c0 <qt_meta_data_PsiApplication>, static_metacall = 0x5555558b58a0 <PsiApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}}
        keystoremgr = <unvollständiger Typ>
        cmdlines = {{d = 0x7ffff5e99520 <QHashData::shared_null>, e = 0x7ffff5e99520 <QHashData::shared_null>}}
        clIt = {c = {{d = 0x7ffff5e99520 <QHashData::shared_null>, e = 0x7ffff5e99520 <QHashData::shared_null>}}, i = {i = 0x7ffff5e99520 <QHashData::shared_null>}, n = {i = 0x7ffff5e99520 <QHashData::shared_null>}}
        psi = 0x5555563b9a80
        returnValue = <optimized out>
```

Package: psi-plus
Version: 1.0.116-0ppa1~xenial1

**Comment by cweiske** [comment]
Updated with all-thread backtrace.

**Comment by Ri0n** [comment]
This one may be fixed with https://github.com/psi-im/psi/commit/b7039c495f53c7d7a477087cfd931f5dc36cbb22

**Comment by cweiske** [comment]
Ok, I got this today again wtih 1.0.120 (which does not contain the patch you mentioned).

**Comment by Ri0n** [comment]
What's about now? We had more fixes to roster.

**Comment by cweiske** [comment]
I had no crash related to resuming anymore in the last 14 days. Closing that here.
