### ISSUE TITLE
Crash on deleting still connecting/updating account just from Psi

### ISSUE THREAD

**Issue by Ri0n** [psi-im/psi#298]
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000006cd0c6 in Alertable::alerting (this=0x18) at alertable.cpp:50
50              return alert_ != 0;
[Current thread is 1 (Thread 0x7f64eb57e8c0 (LWP 3509))]
(gdb) bt full
#0  0x00000000006cd0c6 in Alertable::alerting (this=0x18) at alertable.cpp:50
No locals.
#1  0x000000000078e2de in PsiAccount::alerting (this=0x31be5b0) at psiaccount.cpp:6566
No locals.
#2  0x0000000000863a91 in ContactListItem::value (this=0x2ff0fb0, role=267) at contactlistitem.cpp:512
        res = {d = {data = {c = 0 '\000', uc = 0 '\000', s = 0, sc = 0 '\000', us = 0, i = 0, u = 0, l = 0, ul = 0, b = false, d = 0, f = 0, real = 0, ll = 0, ull = 0, o = 0x0, ptr = 0x0, 
              shared = 0x0}, type = 0, is_shared = 0, is_null = 1}}
#3  0x000000000083436c in ContactListModel::data (this=0x44de270, index=..., role=267) at contactlistmodel.cpp:624
        item = 0x2ff0fb0
#4  0x00007f64e7507939 in QSortFilterProxyModel::data(QModelIndex const&, int) const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#5  0x00000000006a17ae in QModelIndex::data (this=0x7ffde2198210, arole=267) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qabstractitemmodel.h:420
No locals.
#6  0x0000000000842b6a in ContactListViewDelegate::Private::statusPixmap (this=0x3d667d0, index=...) at contactlistviewdelegate.cpp:426
        alert = 255
        item = 0x2ff0fb0
        type = ContactListItem::Type::AccountType
        s = 56166496
#7  0x000000000084721f in ContactListViewDelegate::Private::drawAccount (this=0x3d667d0, painter=0x7ffde21986d0, index=...) at contactlistviewdelegate.cpp:979
        o = {<QStyleOption> = {version = 4, type = 10, state = {i = 2097153}, direction = Qt::LeftToRight, rect = {x1 = 0, y1 = 287, x2 = 223, y2 = 306}, fontMetrics = {d = {d = 0x3590860}}, 
            palette = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7f64e7de19a0, data = 0x7f64e7de1840, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, 
              d = 0x6415cc0, {data = {current_group = 2, resolve_mask = 576}, for_faster_swapping_dont_use = 9218}}, styleObject = 0x0}, displayAlignment = {i = 129}, decorationAlignment = {
            i = 132}, textElideMode = Qt::ElideRight, decorationPosition = QStyleOptionViewItem::Left, decorationSize = {wd = -1, ht = -1}, font = {static staticMetaObject = {d = {
                superdata = 0x0, stringdata = 0x7f64e7de55a0, data = 0x7f64e7de54e0, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = {d = 0x3590860}, resolve_mask = 895}, 
          showDecorationSelected = true, features = {i = 2}, locale = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7f64e7707a60, data = 0x7f64e7706240, static_metacall = 0x0, 
                relatedMetaObjects = 0x0, extradata = 0x0}}, d = {d = 0x59d44c0}}, widget = 0x40fdbc0, index = {r = -1, c = -1, i = 0, m = 0x0}, checkState = Qt::Unchecked, icon = {d = 0x0}, 
          text = {static null = {<No data fields>}, d = 0x7f64e760f3e0 <QArrayData::shared_null>}, viewItemPosition = QStyleOptionViewItem::OnlyOne, backgroundBrush = {d = {d = 0x152b600}}}
        palette = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7f64e7de19a0, data = 0x7f64e7de1840, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, 
          d = 0x6415cc0, {data = {current_group = 2, resolve_mask = 576}, for_faster_swapping_dont_use = 9218}}
        statusPixmap = <incomplete type>
        pixmapSize = {wd = -501645888, ht = 32765}
        statusIconRect = {x1 = 50270128, y1 = 0, x2 = 16611968, y2 = 0}
        text = {static null = {<No data fields>}, d = 0x0}
        r = {x1 = -501645696, y1 = 32765, x2 = 4945500, y2 = 0}
        sslPixmap = <incomplete type>
        sslPixmapSize = {wd = 0, ht = 0}
        sslRect = {x1 = -501645664, y1 = 32765, x2 = 8556564, y2 = 0}
#8  0x0000000000848e26 in ContactListViewDelegate::paint (this=0x1600e90, painter=0x7ffde21986d0, option=..., index=...) at contactlistviewdelegate.cpp:1233
        item = 0x2ff0fb0
        type = ContactListItem::Type::AccountType
#9  0x00007f64ea6d0904 in QTreeView::drawRow(QPainter*, QStyleOptionViewItem const&, QModelIndex const&) const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#10 0x0000000000830a07 in HoverableTreeView::drawRow (this=0x40fdbc0, painter=0x7ffde21986d0, options=..., index=...) at hoverabletreeview.cpp:126
        opt = {<QStyleOptionViewItem> = {<QStyleOption> = {version = 5, type = 10, state = {i = 2097153}, direction = Qt::LeftToRight, rect = {x1 = 0, y1 = 287, x2 = 223, y2 = 306}, 
              fontMetrics = {d = {d = 0x152c720}}, palette = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7f64e7de19a0, data = 0x7f64e7de1840, static_metacall = 0x0, 
                    relatedMetaObjects = 0x0, extradata = 0x0}}, d = 0x3e3c7c0, {data = {current_group = 2, resolve_mask = 512}, for_faster_swapping_dont_use = 8194}}, styleObject = 0x40fdbc0}, 
            displayAlignment = {i = 129}, decorationAlignment = {i = 132}, textElideMode = Qt::ElideRight, decorationPosition = QStyleOptionViewItem::Left, decorationSize = {wd = -1, ht = -1}, 
            font = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7f64e7de55a0, data = 0x7f64e7de54e0, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = {
---Type <return> to continue, or q <return> to quit---
                d = 0x152c720}, resolve_mask = 0}, showDecorationSelected = false, features = {i = 0}, locale = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7f64e7707a60, 
                  data = 0x7f64e7706240, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = {d = 0x59d44c0}}, widget = 0x40fdbc0, index = {r = -1, c = -1, i = 0, m = 0x0}, 
            checkState = Qt::Unchecked, icon = {d = 0x0}, text = {static null = {<No data fields>}, d = 0x7f64e760f3e0 <QArrayData::shared_null>}, 
            viewItemPosition = QStyleOptionViewItem::Invalid, backgroundBrush = {d = {d = 0x152b600}}}, hovered = false, hoveredPosition = {xp = 0, yp = 0}}
        r = {x1 = 0, y1 = 288, x2 = 223, y2 = 307}
#11 0x00007f64ea6d5faf in QTreeView::drawTree(QPainter*, QRegion const&) const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#12 0x00007f64ea6da846 in QTreeView::paintEvent(QPaintEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#13 0x000000000082ace2 in ContactListDragView::paintEvent (this=0x40fdbc0, e=0x7ffde2198e10) at contactlistdragview.cpp:290
No locals.
#14 0x00007f64ea473e58 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#15 0x00007f64ea574b2e in QFrame::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#16 0x00007f64ea69db23 in QAbstractItemView::viewportEvent(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#17 0x00007f64ea6db79c in QTreeView::viewportEvent(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#18 0x0000000000828610 in ContactListView::viewportEvent (this=0x40fdbc0, event=0x7ffde2198e10) at contactlistview.cpp:323
No locals.
#19 0x00007f64e7543012 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#20 0x00007f64ea42ead5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#21 0x00007f64ea434036 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#22 0x00000000006d6023 in PsiApplication::notify (this=0x7ffde219acd0, receiver=0x2386fc0, event=0x7ffde2198e10) at psiapplication.cpp:378
No locals.
#23 0x00007f64e75432a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#24 0x00007f64ea46cd0a in QWidgetPrivate::sendPaintEvent(QRegion const&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#25 0x00007f64ea46d351 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#26 0x00007f64ea46e02c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#27 0x00007f64ea46df19 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#28 0x00007f64ea46df19 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#29 0x00007f64ea46cec1 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#30 0x00007f64ea46e02c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#31 0x00007f64ea46cec1 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#32 0x00007f64ea46e02c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#33 0x00007f64ea46cec1 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#34 0x00007f64ea46e02c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#35 0x00007f64ea46cec1 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#36 0x00007f64ea46e02c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#37 0x00007f64ea46cec1 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#38 0x00007f64ea46e02c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#39 0x00007f64ea46cec1 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#40 0x00007f64ea43c959 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#41 0x00007f64ea43cb4f in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#42 0x00007f64ea45c3af in QWidgetPrivate::syncBackingStore() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#43 0x00007f64ea473f28 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#44 0x00007f64ea58c4bb in QMainWindow::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#45 0x00007f64ea42eafc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#46 0x00007f64ea434036 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#47 0x00000000006d6023 in PsiApplication::notify (this=0x7ffde219acd0, receiver=0x3676940, event=0x6179140) at psiapplication.cpp:378
No locals.
#48 0x00007f64e75432a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#49 0x00007f64e754516a in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#50 0x00007f64e7597f53 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#51 0x00007f64e570e197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#52 0x00007f64e570e3f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
```

**Comment by Ri0n** [comment]
tried several times. can't reproduce anymore.
Probably a fix I did for crash on exit also fixed this issue
